name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Navigate to backend directory
      run: cd ./backend
    - name: Install modules
      run: npm ci
    - name: Run tests
      run: npm test